# frozen_string_literal: true

source 'https://rubygems.org'

gemspec

ENV['rails'] ||= '8.0.0'
gem 'rails', "~> #{ENV['rails']}"
gem 'rails-controller-testing'
gem 'rspec-rails'
gem 'factory_bot'
gem 'sqlite3', '>= 1.3.6'
gem 'bigdecimal'
gem 'mutex_m'

# Optional: doorkeeper-openid_connect for DiscoveryExtension and integration tests.
# When extracted to a standalone repo, replace with: gem 'doorkeeper-openid_connect', '~> 1.0'
gem 'doorkeeper-openid_connect', path: '../..'
